FROM zenika/alpine-chrome:with-node

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD 1
ENV PUPPETEER_EXECUTABLE_PATH /usr/bin/chromium-browser
COPY --chown=chrome . /beepboop
WORKDIR /beepboop
RUN npm install
RUN npm install ytdl-core@latest
ENTRYPOINT ["tini", "--"]
CMD ["npm", "run", "update-ytdl-start"]