version: '3.5'
services:
  node-chrome:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - 8080:8081 # Node web server
    volumes:
      - ./config.json:/beepboop/config.json:ro
    environment:
      - STEAM_USERNAME=${STEAM_USERNAME}
      - STEAM_PASSWORD=${STEAM_PASSWORD}
      - MODE=web
      - DB_CONNECTION=postgres://beepboop:beepboop@db/beepboop
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=beepboop
      - POSTGRES_PASSWORD=beepboop
      - POSTGRES_DB=beepboop
    expose:
      - 5432
    volumes: 
      - ./db:/var/lib/postgresql/data