version: '3.5'
services:
  steam:
    build:
      context: .
      shm_size: '2gb'
    shm_size: '2gb'
    ports:
      - 6080:80
      - 5900:5900
    volumes:
      - steam-client:/home/beepboop/.steam
    environment:
      - STEAM_USERNAME=${STEAM_USERNAME}
      - STEAM_PASSWORD=${STEAM_PASSWORD}
      - MODE=client
    deploy:
      resources:
        limits:
          memory: 1024M
volumes:
  steam-client: